--- 
 - name: Installing python 
  hosts: PIP
  become: yes
  become_method: sudo
  tasks:
  - name: install python
  yum: name={{ item }} update_cache=yes state=latest
  with_items:
  - python
- name: Installing Vagrant 
  hosts: PIP
  become: yes
  become_method: sudo
  tasks:
  - name: install Vagrant package
  command: wget https://releases.hashicorp.com/vagrant/2.2.9/vagrant_2.2.9_x86_64.deb
  yum: name={{ item }} update_cache=yes state=latest
  with_items:
  - vagrant_2.2.9_x86_64.deb
 - name: Installing virtualbox 
  hosts: PIP
  become: yes
  become_method: sudo
  tasks:
  - name: install Virtual box
    yum: name={{ item }} update_cache=yes state=latest
  with_items:
  - virtualbox