---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
          - name: myapp
            image: santoshpandey11/myapp
            ports:
              - containerPort: 8000
            resources:
              requests:
                memory: "512Mi"
                cpu: "250m"
              limits:
                memory: "1024Mi"
                cpu: "500m"

----
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp
  ports:
    - port: 8000
      targetPort: 8000
  type: LoadBalancer
